fix macos workflow

diff --git a/.github/workflows/build_macos_arm64_wheels.yml b/.github/workflows/build_macos_arm64_wheels.yml
--- a/.github/workflows/build_macos_arm64_wheels.yml
+++ b/.github/workflows/build_macos_arm64_wheels.yml
@@ -78,7 +78,12 @@ jobs:
           brew update
           brew install ca-certificates lz4 mpdecimal openssl@3 readline sqlite xz z3 zstd
           brew install --ignore-dependencies llvm@19
-          brew install git ninja libtool gettext gcc binutils grep findutils nasm lld
+          export PATH=$(brew --prefix llvm@19)/bin:$PATH
+          # Check if wasm-ld is available, if not link from lld
+          if ! which wasm-ld; then
+            ln -sf $(brew --prefix llvm@19)/bin/ld.lld $(brew --prefix llvm@19)/bin/wasm-ld || echo "Could not create wasm-ld symlink"
+          fi
+          brew install git ninja libtool gettext gcc binutils grep findutils nasm
           brew install --build-from-source ccache || echo "ccache installation failed, continuing without it"
           brew install go
           cd /usr/local/opt/ && sudo rm -f llvm && sudo ln -sf llvm@19 llvm
